import 'package:coco_explorer/models/suggestion_model.dart';

List<SuggestionModel> suggestionList = [
  SuggestionModel(title: 'toilet', id: 70,),
  SuggestionModel(title: 'teddy bear', id: 88,),
  SuggestionModel(title: 'cup', id: 47,),
  SuggestionModel(title: 'bicycle', id: 2,),
  SuggestionModel(title: 'kite', id: 38,),
  SuggestionModel(title: 'carrot', id: 57,),
  SuggestionModel(title: 'stop sign', id: 13,),
  SuggestionModel(title: 'tennis racket', id: 43,),
  SuggestionModel(title: 'donut', id: 60,),
  SuggestionModel(title: 'snowboard', id: 36,),
  SuggestionModel(title: 'sandwich', id: 54,),
  SuggestionModel(title: 'motorcycle', id: 4,),
  SuggestionModel(title: 'oven', id: 79,),
  SuggestionModel(title: 'keyboard', id: 76,),
  SuggestionModel(title: 'scissors', id: 87,),
  SuggestionModel(title: 'airplane', id: 5,),
  SuggestionModel(title: 'couch', id: 63,),
  SuggestionModel(title: 'mouse', id: 74,),
  SuggestionModel(title: 'fire hydrant', id: 11,),
  SuggestionModel(title: 'boat', id: 9,),
  SuggestionModel(title: 'apple', id: 53,),
  SuggestionModel(title: 'sheep', id: 20,),
  SuggestionModel(title: 'horse', id: 19,),
  SuggestionModel(title: 'banana', id: 52,),
  SuggestionModel(title: 'baseball glove', id: 40,),
  SuggestionModel(title: 'tv', id: 72,),
  SuggestionModel(title: 'traffic light', id: 10,),
  SuggestionModel(title: 'chair', id: 62,),
  SuggestionModel(title: 'bowl', id: 51,),
  SuggestionModel(title: 'microwave', id: 78,),
  SuggestionModel(title: 'bench', id: 15,),
  SuggestionModel(title: 'book', id: 84,),
  SuggestionModel(title: 'elephant', id: 22,),
  SuggestionModel(title: 'orange', id: 55,),
  SuggestionModel(title: 'tie', id: 32,),
  SuggestionModel(title: 'clock', id: 85,),
  SuggestionModel(title: 'bird', id: 16,),
  SuggestionModel(title: 'knife', id: 49,),
  SuggestionModel(title: 'pizza', id: 59,),
  SuggestionModel(title: 'fork', id: 48,),
  SuggestionModel(title: 'hair drier', id: 89,),
  SuggestionModel(title: 'frisbee', id: 34,),
  SuggestionModel(title: 'umbrella', id: 28,),
  SuggestionModel(title: 'bottle', id: 44,),
  SuggestionModel(title: 'bus', id: 6,),
  SuggestionModel(title: 'bear', id: 23,),
  SuggestionModel(title: 'vase', id: 86,),
  SuggestionModel(title: 'toothbrush', id: 90,),
  SuggestionModel(title: 'spoon', id: 50,),
  SuggestionModel(title: 'train', id: 7,),
  SuggestionModel(title: 'sink', id: 81,),
  SuggestionModel(title: 'potted plant', id: 64,),
  SuggestionModel(title: 'handbag', id: 31,),
  SuggestionModel(title: 'cell phone', id: 77,),
  SuggestionModel(title: 'toaster', id: 80,),
  SuggestionModel(title: 'broccoli', id: 56,),
  SuggestionModel(title: 'refrigerator', id: 82,),
  SuggestionModel(title: 'laptop', id: 73,),
  SuggestionModel(title: 'remote', id: 75,),
  SuggestionModel(title: 'surfboard', id: 42,),
  SuggestionModel(title: 'cow', id: 21,),
  SuggestionModel(title: 'dining table', id: 67,),
  SuggestionModel(title: 'hot dog', id: 58,),
  SuggestionModel(title: 'car', id: 3,),
  SuggestionModel(title: 'sports ball', id: 37,),
  SuggestionModel(title: 'skateboard', id: 41,),
  SuggestionModel(title: 'dog', id: 18,),
  SuggestionModel(title: 'bed', id: 65,),
  SuggestionModel(title: 'cat', id: 17,),
  SuggestionModel(title: 'person', id: 1,),
  SuggestionModel(title: 'skis', id: 35,),
  SuggestionModel(title: 'giraffe', id: 25,),
  SuggestionModel(title: 'truck', id: 8,),
  SuggestionModel(title: 'parking meter', id: 14,),
  SuggestionModel(title: 'suitcase', id: 33,),
  SuggestionModel(title: 'cake', id: 61,),
  SuggestionModel(title: 'wine glass', id: 46,),
  SuggestionModel(title: 'baseball bat', id: 39,),
  SuggestionModel(title: 'backpack', id: 27,),
  SuggestionModel(title: 'zebra', id: 24),
];